### ISSUE TITLE
Where is the endpoint URL of API Gateway?

### ISSUE THREAD

**Issue by bsg-bob** [aws-samples/amazon-pinpoint-call-generator#1]
I deployed, but the end-point URL is not set.

**Comment by ghost** [comment]
Hi. The solution as coded noes not include an API Gateway end point. The original design was to allow events inside of AWS to trigger the phone calls. If you need API Gateway access to trigger phone calls you would need to edit the  template.yaml to add the API Gateway to the CallGeneratorFunction definition.
